name: Build and Deploy to GitHub Pages

# main 브랜치에 push될 때 트리거
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# GitHub Pages 배포를 위한 권한 설정
permissions:
  contents: read
  pages: write
  id-token: write

# 동시 배포 방지
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # 빌드 및 테스트 작업
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout 코드
      uses: actions/checkout@v4
      
    - name: Node.js 설정
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: 의존성 설치
      run: npm ci
      
    - name: 린트 검사
      run: npm run lint
      
    - name: 프로덕션 빌드
      run: npm run build
      
    - name: 빌드 결과 상세 확인
      run: |
        echo "=== 빌드 결과 확인 ==="
        ls -la dist/
        echo ""
        echo "=== dist 디렉토리 내용 ==="
        find dist -type f -name "*.html" -o -name "*.js" -o -name "*.css" | head -20
        echo ""
        echo "=== index.html 존재 및 내용 확인 ==="
        if [ -f dist/index.html ]; then
          echo "✅ index.html 존재"
          echo "=== index.html 첫 10줄 ==="
          head -10 dist/index.html
        else
          echo "❌ index.html 없음"
          echo "=== dist 디렉토리 전체 구조 ==="
          tree dist/ || find dist -type f
        fi
        
    - name: 빌드 아티팩트 업로드
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./dist

  # GitHub Pages 배포 작업
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - name: 배포 전 환경 확인
      run: |
        echo "=== GitHub Pages 환경 확인 ==="
        echo "Repository: ${{ github.repository }}"
        echo "Branch: ${{ github.ref_name }}"
        echo "Event: ${{ github.event_name }}"
        
    - name: GitHub Pages 배포
      id: deployment
      uses: actions/deploy-pages@v4
      
    - name: 배포 결과 확인
      run: |
        echo "=== 배포 완료 ==="
        echo "배포 URL: ${{ steps.deployment.outputs.page_url }}"
        echo "예상 URL: https://yanggangyiplus.github.io/persona-chronicle-hub/"
